### PR TITLE
Add Timeshift to PVR Video OSD

### PR DESCRIPTION
**Pull request by FXB78**
For Live TV/PVR I have added in Timeshift and switched over the Start Time & Current Time to better accommodate this.

### CODE REVIEW

**Comment by nfm886** [comment]
Hey!
Thanks to your contribution! I can merge it. Will be pushed with update for a couple of minutes :)

**Comment by FXB78** [comment]
Hi, I think I messed it up :) I deleted the file because it seemed to reverse your flag changes as I was on the main branch.

If you let me know what to do I can try again!

**Comment by nfm886** [comment]
Yes, I see ^^ I will revert PR and please make another one :P

**Comment by FXB78** [comment]
Sorry about that... I will try again!

**Comment by nfm886** [comment]
It's fine :)
To be honest I'm not familiar with GitHub. Just know some basics so chill :D

**Pull request merged**
